backend: nccl
data:
    batch_size: 12
    train_dir: /home/mifore/band2band/data/chip_256/train
    val_dir: /home/mifore/band2band/data/chip_256/val
device: cuda
loss:
    matching:
        type: L2
        weight: 0.2
    reconstruction_gen:
        type: L2
        weight: 0.5
    reconstruction_self:
        type: L2
        weight: 0.3
model:
    decoder:
        const_blocks: 2
        const_channel_divisor: 2
        input_channels: 128
        mode: bilinear
        num_classes: 14
        output_channels: 1
        scale_factor: 2
        up_blocks: 3
        up_channel_divisor: 2
    encoder:
        const_blocks: 2
        const_channel_multiplier: 1
        down_blocks: 3
        down_channel_multiplier: 2
        first_out_channels: 32
        input_channels: 1
        num_classes: 14
        pooling_factor: 2
model_dir: /home/mifore/band2band/model_dir/aml_test0/
optimizer:
    algorithm: adam
    learning_rate: 0.001
    momentum: 0.9
training:
    checkpoint_dir: output/checkpoints/aml_test0/
    checkpoint_every: 50
    iterations: 500
    log_directory: logs/aml_test0
    log_every: 50
validation:
    do_validation: true
    iterations: 50
    val_every: 50
