backend: nccl
data:
    batch_size: 12
    dir_head: /home/mifore/band2bad/data/chip_256
    train_csv: train_pairs.csv
    val_csv: val_pairs.csv
    num_workers: 4
loss:
    matching:
        type: L2
        weight: 0.0
    reconstruction_gen:
        type: L2
        weight: 1.0
    reconstruction_self:
        type: L2
        weight: 0.0
model:
    decoder:
        const_blocks: 2
        const_channel_divisor: 2
        input_channels: 128
        mode: bilinear
        num_classes: 14
        output_channels: 1
        scale_factor: 2
        up_blocks: 3
        up_channel_divisor: 2
    encoder:
        const_blocks: 2
        const_channel_multiplier: 1
        down_blocks: 3
        down_channel_multiplier: 2
        first_out_channels: 32
        input_channels: 1
        num_classes: 14
        pooling_factor: 2
model_dir: outputs/run0
training:
    optimizer:
        algorithm: adam
        learning_rate: 0.001
        momentum: 0.9
    checkpoint_dir: outputs/run0/checkpoints/
    iterations: 30
    logging:
        directory: logs/run0
        log_every: 5
        logger: aml
validation:
    do_validation: true
    iterations: 10
    val_every: 10
checkpoint:
    encoder: Encoder_final.pth
    decoder: Decoder_final.pth
aml:
    use_aml: true
    aml_config: aml/aml_config.json
    experiment_name: debugging
    compute:
        use_instance: false
        name: gpu-cluster
    process_count: 4
    node_count: 2
    dataset: b2b
