backend: nccl
data:
    batch_size: 12
    dir_head: /home/mifore/band2bad/data/chip_256
    train_csv: train_pairs.csv
    val_csv: val_pairs.csv
    num_workers: 4
loss:
    matching:
        type: L2
        weight: 0.0
    reconstruction_gen:
        type: L2
        weight: 1.0
    reconstruction_self:
        type: L2
        weight: 0.0
    validate:
        type: L2
model:
    up_down_blocks: 3
    up_down_channel_multiplier: 2
    const_channel_multiplier: 1
    const_blocks_per: 2
    scale_pooling_factor: 2
    decoder:
        mode: bilinear
        num_classes: 14
        output_channels: 1
    encoder:
        first_out_channels: 32
        input_channels: 1
        num_classes: 14
model_dir: outputs/run0
training:
    optimizer:
        algorithm: adam
        learning_rate: 0.001
        momentum: 0.9
    checkpoint_dir: outputs/run0/checkpoints/
    iterations: 5000
    logging:
        directory: logs/run0
        log_every: 50
        logger: aml
validation:
    do_validation: true
    iterations: 50
    val_every: 50
checkpoint:
    encoder: Encoder_final.pth
    decoder: Decoder_final.pth
aml:
    use_aml: true
    aml_config: aml/aml_config.json
    experiment_name: hyperdrive
    compute:
        use_instance: false
        name: gpu-cluster
    process_count: 4
    node_count: 3
    dataset: b2b
