model:
    encoder:
          input_channels: 1
          down_blocks: 3
          const_blocks: 2
          pooling_factor: 2
          internal_embeddings: true
          first_out_channels: 32
          down_channel_multiplier: 2
          const_channel_multiplier: 1
          num_classes: 14
    decoder:
          input_channels: 128
          up_blocks: 3
          const_blocks: 2
          scale_factor: 2
          mode: "bilinear"
          internal_embeddings: true
          up_channel_divisor: 2
          const_channel_divisor: 2
          output_channels: 1
          num_classes: 14
loss:
    reconstruction_self: 
        type: 'L2'
        weight: 0.25
    reconstruction_gen: 
        type: 'L2'
        weight: 0.5
    matching: 
        type: 'L2'
        weight: 0.25
optimizer: 
    algorithm: "adam"
    learning_rate: .001
    momentum: 0.9
data:
    train_dir: "/home/mifore/band2band/data/train"
    val_dir: "/home/mifore/band2band/data/val"
    shuffle: true 
    image_size: 256
    batch_size: 24
iterations: 3000
log_every: 20
log_directory: 'runs'
checkpoint_every: 100
checkpoint_dir: 'checkpoints'

